### ISSUE TITLE
License: need approval by contributors for change it from GPL to BSD-3

### ISSUE THREAD

**Issue by miksask** [stefantalpalaru/django-pygments#1]
@stefantalpalaru, even considering that most of the commits in this lib are yours, it might not be safe to change the license from GPL to BSD without a formal approval from other authors.

I think that it might be just an "I agree" text in this issue from the other commiters.

**Comment by stefantalpalaru** [comment]
Dear contributors, please confirm that you agree with the [license change](https://github.com/stefantalpalaru/django-pygments/commit/ac0fcf1f8183d7476acec3d6e59f1a6951cb721a) from April 30 2014 (GPLv3 -> 3-clause BSD). Thanks.

@madhusudancs, @djm, @georgedorn, @valeriansaliou, @flupke, @mjtamlyn.

**Comment by djm** [comment]
Confirmed, I agree.

**Comment by georgedorn** [comment]
Yeah, don't let my one-word patch stand in your way.

**Comment by valeriansaliou** [comment]
Same.

**Comment by flupke** [comment]
Ok

Le sam. 20 avr. 2019 à 08:03, Valerian Saliou <notifications@github.com> a
écrit :

**Comment by mjtamlyn** [comment]
I agree
