### ISSUE TITLE
Cannot Import 'smart text' from django.utils.encoding 

### ISSUE THREAD

**Issue by babucarr32** [stefantalpalaru/django-pygments#4]
Hi am using django-pygments, but am recieving this error. 
ImportError raised when trying to load 'django_pygments.templatetags.pygmentify': cannot import name 'smart_text' from 'django.utils.encoding' (/home/babu/.local/lib/python3.10/site-packages/django/utils/encoding.py)
Am using django-4.1.5. Please help.

**Comment by stefantalpalaru** [comment]
"smart_text" was deprecated in Django 3 and removed in 4: https://docs.djangoproject.com/en/4.0/releases/3.0/#deprecated-features-3-0

**Comment by stefantalpalaru** [comment]
This should work though: https://github.com/stefantalpalaru/django-pygments/blob/724954c892ab65db83583594da7cd5a57153c6e2/django_pygments/utils.py#L9

Can you try it from a Django shell and report the error message?

**Comment by stefantalpalaru** [comment]
You were probably using version 0.4 which did not have the Django 4 fix. I just released 0.5 which should fix your problem.
