### ISSUE TITLE
[enhancement] Make the line numbering to be an opt-in

### ISSUE THREAD

**Issue by psam44** [stefantalpalaru/django-pygments#7]
Currently the line numbering is imposed. I would prefer it to be of my choice.
About the argue to ease a copy-paste operation without the numbers, notice that the "table" variant is precisely designed for that.

The enhancement simply implies an additional `list` option for `linenos`. As the default behaviour is now the same as the native Pygments, that is without numbering, it may be considered as a breaking change.

Examples (with a selection, to reveal if the numbers are included or not).
```
{% pygment linenos="list" %}
```
![image](https://github.com/user-attachments/assets/75a9f491-8f1e-44c1-9f4f-5bb4cd11257d)

The following cases are native ones (without any dedicated css here).
```
{% pygment %}
```
![image](https://github.com/user-attachments/assets/dba1e165-d45e-4cb5-b921-8f5e8acdf4d4)

```
{% pygment linenos="table" %}
```
![image](https://github.com/user-attachments/assets/279cd70a-e88c-450d-9e47-d9a9da437384)

```
{% pygment linenos="inline" %}
```
![image](https://github.com/user-attachments/assets/1c0e5818-8d6f-45c6-bd69-e3d7487d4323)

The implementation:
```diff
@@ -31,7 +37,12 @@
         lexers_iter = LEXERS.values()
     lexer_names = reduce(lambda a,b: a + b[2], lexers_iter, ())
     # custom formatter
-    formatter = ListHtmlFormatter(encoding='utf-8', **kwargs)
+    if kwargs.get('linenos', False) == 'list':
+        del kwargs['linenos']
+        formatter_class = ListHtmlFormatter
+    else:
+        formatter_class = HtmlFormatter
+    formatter = formatter_class(encoding='utf-8', **kwargs)
     subs = []
     pre_re = re.compile(r'(<pre[^>]*>)(.*?)(</pre>)', re.DOTALL | re.UNICODE)
     br_re = re.compile(r'<br[^>]*?>', re.UNICODE)
```

**Comment by stefantalpalaru** [comment]
> As the default behaviour is now the same as the native Pygments, that is without numbering, it may be considered as a breaking change.

No need to change the default behaviour. We can require `linenos="none"` to disable line numbering.

**Comment by psam44** [comment]
In that case, the implementation becomes:
```diff
@@ -31,7 +38,10 @@
         lexers_iter = LEXERS.values()
     lexer_names = reduce(lambda a,b: a + b[2], lexers_iter, ())
     # custom formatter
-    formatter = ListHtmlFormatter(encoding='utf-8', **kwargs)
+    linenos = kwargs.get('linenos', False)
+    if linenos == 'none':
+        del kwargs['linenos']
+    formatter = (HtmlFormatter if linenos else ListHtmlFormatter)(encoding='utf-8', **kwargs)
     subs = []
     pre_re = re.compile(r'(<pre[^>]*>)(.*?)(</pre>)', re.DOTALL | re.UNICODE)
     br_re = re.compile(r'<br[^>]*?>', re.UNICODE)
```
And the first two examples are respectively for:
```
{% pygment %}
```
```
{% pygment linenos="none" %}
```

**Comment by stefantalpalaru** [comment]
Line numbering can now be disabled with: `{% pygment linenos=False %} ...` - which avoids introducing any non-standard syntax for `pygments.formatters.HtmlFormatter` arguments.
