### ISSUE TITLE
Redundant <div> wrapping

### ISSUE THREAD

**Issue by psam44** [stefantalpalaru/django-pygments#8]
![image](https://github.com/user-attachments/assets/efe28820-3c82-4670-ad67-b0d5b2dbd0dc)

On pygments 2.12.0 (on Apr 24, 2022), the `self._wrap_div()` has migrated from `def wrap` to `def format_unencoded`.
So you need to remove it from the `wrap()` of `ListHtmlFormatter`.

```diff
 class ListHtmlFormatter(HtmlFormatter):
    def wrap(self, source):
-        return self._wrap_div(self._wrap_pre(self._wrap_list(source)))
+        return self._wrap_pre(self._wrap_list(source))
```

**Comment by stefantalpalaru** [comment]
Fixed. Thanks!
